# Generated by Django 5.2 on 2025-04-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ukol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popis', models.CharField(max_length=255)),
                ('splneno', models.BooleanField(default=False)),
            ],
        ),
    ]
