# Generated by Django 5.2 on 2025-05-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pocasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teplota', models.CharField(max_length=255)),
                ('pocitova_teplota', models.CharField(max_length=255)),
                ('stav_pocasi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Uzivatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=255)),
                ('heslo', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='ukol',
            name='nazev',
            field=models.CharField(default='Bez názvu', max_length=255),
            preserve_default=False,
        ),
    ]
