services:
  - type: web
    name: todo-app
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn todo_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: todo-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

databases:
  - name: todo-db
    plan: free
